// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVeeq_oMMMuhZIZK81_js6kANtTynd5qk',
    appId: '1:919773132515:web:5e8366d547011a5bcb37d6',
    messagingSenderId: '919773132515',
    projectId: 'kmit-college-canteen-1',
    authDomain: 'kmit-college-canteen-1.firebaseapp.com',
    storageBucket: 'kmit-college-canteen-1.firebasestorage.app',
    measurementId: 'G-3X9D7TP1LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtfVtjbbRWOjd0TmcMEPyGF4GcbH-l5X4',
    appId: '1:919773132515:android:967e5dc9035625a3cb37d6',
    messagingSenderId: '919773132515',
    projectId: 'kmit-college-canteen-1',
    storageBucket: 'kmit-college-canteen-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-esfu_-cewhrrc56g855Jnsw8oBmj2o',
    appId: '1:919773132515:ios:1b565a1f5458415ccb37d6',
    messagingSenderId: '919773132515',
    projectId: 'kmit-college-canteen-1',
    storageBucket: 'kmit-college-canteen-1.firebasestorage.app',
    iosBundleId: 'com.example.kmitCanteenClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE-esfu_-cewhrrc56g855Jnsw8oBmj2o',
    appId: '1:919773132515:ios:1b565a1f5458415ccb37d6',
    messagingSenderId: '919773132515',
    projectId: 'kmit-college-canteen-1',
    storageBucket: 'kmit-college-canteen-1.firebasestorage.app',
    iosBundleId: 'com.example.kmitCanteenClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVeeq_oMMMuhZIZK81_js6kANtTynd5qk',
    appId: '1:919773132515:web:ee5ebd2bc7008448cb37d6',
    messagingSenderId: '919773132515',
    projectId: 'kmit-college-canteen-1',
    authDomain: 'kmit-college-canteen-1.firebaseapp.com',
    storageBucket: 'kmit-college-canteen-1.firebasestorage.app',
    measurementId: 'G-GLK5BM9G4G',
  );

}